Frecuencias absolutas, relativas y acumuladas

se manejaron frecuencias absolutas, ya que simplemente se contaron los elementos que correspondían a cada valor o a cada clase. Sin
embargo, en algunas aplicaciones conviene manejar las frecuencias de las series no en forma absoluta sino
en forma relativa y también en forma relativa acumulada.

En las tablas de frecuencias acumuladas simplemente se suman las frecuencias de todas las categorías anteriores, de manera que la frecuencia de cualquiera de esas categorías es igual a la suma de
las frecuencias absolutas de todas las categorías precedentes. 

In [1]:
import funciones as fn


In [2]:

focos_defectuosos = [0 , 2 , 1 , 0 , 3 , 0 , 2 , 0 , 0 , 1 , 4 , 2 , 5 , 1 , 0 , 1 , 1 , 0 , 0 , 0 , 1 , 0 , 1 , 1 , 0 , 0 , 0 , 2 , 0 , 1 , 2 , 1 , 0 , 0 , 1 , 1 , 0 , 0 , 0 , 1 , 1 , 0 , 1 , 2 , 3 , 0 , 1 , 0 , 1 , 1]

# obtener el grupo de focos defectuosos
frecuencia_focos = fn.frecuencia(sorted(focos_defectuosos))
assert sum(frecuencia_focos.values()) == len(focos_defectuosos)

tabla = fn.pretty_table (frecuencia_focos, "focos (x)", "Frecuencia (f)")
print(tabla)


+-----------+----------------+
| focos (x) | Frecuencia (f) |
+-----------+----------------+
|     0     |       22       |
|     1     |       18       |
|     2     |       6        |
|     3     |       2        |
|     4     |       1        |
|     5     |       1        |
+-----------+----------------+


In [3]:
frecuencia_fd = fn.distribucion_relativa(frecuencia_focos)
print(frecuencia_fd)


defaultdict(<class 'dict'>, {0: [22, 22, 0.44, 44], 1: [18, 40, 0.36, 36], 2: [6, 46, 0.12, 12], 3: [2, 48, 0.04, 4], 4: [1, 49, 0.02, 2], 5: [1, 50, 0.02, 2]})


In [5]:

# Tabla de frecuencias de focos defectuosos, incluyendo frecuencias acumuladas y frecuencias relativas
table = fn.pretty_table_frec_relativa(
    data=frecuencia_fd, 
    field_names=["Focos Defectuosos", "Frecuencia", "Frec. Acumulada", "Frec. relativa (uso)", "Frec. relativa (%)"])
print(table)

+-------------------+------------+-----------------+----------------------+--------------------+
| Focos Defectuosos | Frecuencia | Frec. Acumulada | Frec. relativa (uso) | Frec. relativa (%) |
+-------------------+------------+-----------------+----------------------+--------------------+
|         0         |     22     |        22       |         0.44         |         44         |
|         1         |     18     |        40       |         0.36         |         36         |
|         2         |     6      |        46       |         0.12         |         12         |
|         3         |     2      |        48       |         0.04         |         4          |
|         4         |     1      |        49       |         0.02         |         2          |
|         5         |     1      |        50       |         0.02         |         2          |
+-------------------+------------+-----------------+----------------------+--------------------+
|       Total       |     50  

Una utilidad práctica fácilmente identificable de las frecuencias relativas y de las acumuladas es que
puede saberse, por ejemplo, la proporción de cada número de artículos defectuosos: puede conocerse
que 44% de las cajas no contiene focos defectuosos y que 36% tienen uno.

********
**DISTRIBUCIÓN DE FRECUENCIAS**: Agrupación de datos en clases mutuamente excluyentes, que muestra el número de observaciones que hay en cada clase
********

*ejemplo 2.6 Elaboración de una serie de datos y frecuencias* 

In [6]:
baterias_duracion = [163 , 159 , 150 , 136 , 136 , 138 , 155 , 158 , 135 , 166 , 132 , 144 , 125 , 157 , 146 , 145 , 145 , 150 , 144 , 142 , 154 , 139 , 139 , 168 , 158 , 151 , 151 , 153 , 148 , 156 , 152 , 146 , 134 , 158 , 154 , 154 , 154 , 151 , 150 , 154 , 148 , 144 , 156 , 167 , 156 , 141 , 141 , 138 , 148 , 160]

Se presentan en la tabla siguiente los tiempos de duración (en
horas) para muestra aleatoria de 50 baterías.

In [7]:
tiempo_duracion_bateria = sorted(baterias_duracion)

frecuencia_baterias = fn.frecuencia(tiempo_duracion_bateria)
assert sum(frecuencia_baterias.values()) == len(baterias_duracion)

tabla = fn.pretty_table (frecuencia_baterias, "focos (x)", "Frecuencia (f)")
print(tabla)

+-----------+----------------+
| focos (x) | Frecuencia (f) |
+-----------+----------------+
|    125    |       1        |
|    132    |       1        |
|    134    |       1        |
|    135    |       1        |
|    136    |       2        |
|    138    |       2        |
|    139    |       2        |
|    141    |       2        |
|    142    |       1        |
|    144    |       3        |
|    145    |       2        |
|    146    |       2        |
|    148    |       3        |
|    150    |       3        |
|    151    |       3        |
|    152    |       1        |
|    153    |       1        |
|    154    |       5        |
|    155    |       1        |
|    156    |       3        |
|    157    |       1        |
|    158    |       3        |
|    159    |       1        |
|    160    |       1        |
|    163    |       1        |
|    166    |       1        |
|    167    |       1        |
|    168    |       1        |
+-----------+----------------+


*ejemplo 2.7 Elaboración de una serie de clases y frecuencias

1. Determine el número de clases o intervalos, utilizando la
raíz cuadrada del número de elementos de la serie. Agrupe
los datos en 7 clases

In [8]:
amplitud_clase_baterias = fn.reglaSturges(frecuencia_baterias)
print(f'Min: {min(baterias_duracion)} max: {max(baterias_duracion)} Intervalo de clase: {amplitud_clase_baterias}')

#trunca el valor de la amplitud de clase
amplitud_clase_baterias = int(amplitud_clase_baterias)

Min: 125 max: 168 Intervalo de clase: 7.166666666666667


2. Determine el rango de los datos: el primero y el último de
los valores de la serie ordenada en Excel (máximo – mínimo) 168 – 125 = 43.

In [9]:
rango_baterias = max(baterias_duracion) - min(baterias_duracion)
print(f'Rango: {rango_baterias}')

Rango: 43


3. Divida el rango entre el número de clases para determinar
los intervalos de clase, por lo que se utiliza un intervalo de
amplitud 7. 

In [10]:
clase_baterias= fn.distribucion_frecuencia(
    tiempo_duracion_bateria, 
    min=int(round(min(baterias_duracion),-1)),
    max=int(max(tiempo_duracion_bateria)), 
    incr = int(amplitud_clase_baterias)
)
assert sum(clase_baterias.values()) == len(baterias_duracion)

tabla = fn.pretty_table (clase_baterias, "Baterias (x)", "Frecuencia (f)")
print(tabla)


+--------------------+----------------+
|    Baterias (x)    | Frecuencia (f) |
+--------------------+----------------+
| 120 a menos de 127 |       1        |
| 127 a menos de 134 |       1        |
| 134 a menos de 141 |       8        |
| 141 a menos de 148 |       10       |
| 148 a menos de 155 |       16       |
| 155 a menos de 162 |       10       |
| 162 a menos de 169 |       4        |
+--------------------+----------------+


In [11]:
frecuencia_fd = fn.distribucion_relativa(frecuencia_baterias)
print(frecuencia_fd)

defaultdict(<class 'dict'>, {125: [1, 1, 0.02, 2], 132: [1, 2, 0.02, 2], 134: [1, 3, 0.02, 2], 135: [1, 4, 0.02, 2], 136: [2, 6, 0.04, 4], 138: [2, 8, 0.04, 4], 139: [2, 10, 0.04, 4], 141: [2, 12, 0.04, 4], 142: [1, 13, 0.02, 2], 144: [3, 16, 0.06, 6], 145: [2, 18, 0.04, 4], 146: [2, 20, 0.04, 4], 148: [3, 23, 0.06, 6], 150: [3, 26, 0.06, 6], 151: [3, 29, 0.06, 6], 152: [1, 30, 0.02, 2], 153: [1, 31, 0.02, 2], 154: [5, 36, 0.1, 10], 155: [1, 37, 0.02, 2], 156: [3, 40, 0.06, 6], 157: [1, 41, 0.02, 2], 158: [3, 44, 0.06, 6], 159: [1, 45, 0.02, 2], 160: [1, 46, 0.02, 2], 163: [1, 47, 0.02, 2], 166: [1, 48, 0.02, 2], 167: [1, 49, 0.02, 2], 168: [1, 50, 0.02, 2]})


In [12]:
# Tabla de frecuencias de duración de baterías, incluyendo frecuencias acumuladas y frecuencias relativas
table = fn.pretty_table_frec_relativa(
    data=frecuencia_fd, 
    field_names=["Horas de duración de baterías", "Frecuencia (f)", "Frec. Acumulada", "Frec. relativa (uso)", "Frec. relativa (%)"])
print(table)

#suma_frecuencia = sum(frecuencia_fd[key][0] for key in frecuencia_fd)
#frec_relativa = sum(frecuencia_fd[key][2] for key in frecuencia_fd)
#print (f'\tTotal: \t {suma_frecuencia}',
#       '\t\tFrec. relativa: \t{0:.2f}'.format(frec_relativa),'\t\t{0:.2f}'.format(frec_relativa*100),' %' )


+-------------------------------+----------------+-----------------+----------------------+--------------------+
| Horas de duración de baterías | Frecuencia (f) | Frec. Acumulada | Frec. relativa (uso) | Frec. relativa (%) |
+-------------------------------+----------------+-----------------+----------------------+--------------------+
|              125              |       1        |        1        |         0.02         |         2          |
|              132              |       1        |        2        |         0.02         |         2          |
|              134              |       1        |        3        |         0.02         |         2          |
|              135              |       1        |        4        |         0.02         |         2          |
|              136              |       2        |        6        |         0.04         |         4          |
|              138              |       2        |        8        |         0.04         |     